/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_PHOEBE (void);
GtkWidget* create_PHOEBE_open_data_file (void);
GtkWidget* create_PHOEBE_calculate_phsv (void);
GtkWidget* create_PHOEBE_calculate_pcsv (void);
GtkWidget* create_PHOEBE_open_keyword_file (void);
GtkWidget* create_PHOEBE_plot_lc (void);
GtkWidget* create_PHOEBE_configuration (void);
GtkWidget* create_PHOEBE_configuration_browse (void);
GtkWidget* create_PHOEBE_plot_rv (void);
GtkWidget* create_PHOEBE_ld_interpolation (void);
GtkWidget* create_PHOEBE_about (void);
GtkWidget* create_PHOEBE_calculate_grid (void);
GtkWidget* create_PHOEBE_assign_data_file (void);
GtkWidget* create_PHOEBE_calculate_grid_edit_parameters (void);
GtkWidget* create_PHOEBE_dc (void);
GtkWidget* create_PHOEBE_assign_lc_luminosity (void);
GtkWidget* create_PHOEBE_assign_rv_data_file (void);
GtkWidget* create_PHOEBE_assign_el3 (void);
GtkWidget* create_PHOEBE_assign_ld_monochromatic_lc (void);
GtkWidget* create_PHOEBE_assign_weighting (void);
GtkWidget* create_PHOEBE_assign_ld_monochromatic_rv (void);
GtkWidget* create_PHOEBE_plot_to_file (void);
GtkWidget* create_PHOEBE_plot_to_file_selector (void);
GtkWidget* create_PHOEBE_fitting_quickbar (void);
GtkWidget* create_PHOEBE_scripter (void);
GtkWidget* create_PHOEBE_filter_menu (void);
GtkWidget* create_PHOEBE_assign_primary_spots (void);
GtkWidget* create_PHOEBE_assign_secondary_spots (void);
GtkWidget* create_PHOEBE_dc_correlation_matrix (void);
GtkWidget* create_PHOEBE_data_sheet (void);
GtkWidget* create_PHOEBE_file_selector (void);
